// Bundles the modular source into ONE self-contained HTML file with CSS and JS
// inlined, then writes it to both:
//   - index.html                    (the deployed homepage)
//   - dist/interval-training.html   (the offline, double-click copy)
//
// Why inline?  Serving the app as separate ES modules makes the browser cache
// each file independently, so after a deploy you can end up running fresh HTML
// against a stale, cached app.js (and a `?v=` on the <script> does NOT cascade
// to its imports). A single self-contained file has nothing to cache out of
// sync, so the live site can never get into that mixed-version state.
//
// Source of truth is `dev.html` + `src/`.  Run: `node build.js`.

const fs = require("fs");
const path = require("path");
const vm = require("vm");

const root = __dirname;
const read = (p) => fs.readFileSync(path.join(root, p), "utf8");

function stripModuleSyntax(src) {
  return src
    .replace(/^\s*import[^;]*;?\s*$/gm, "") // drop `import ... from "..."`
    .replace(/^\s*export\s+/gm, "");        // `export class/function/const` -> bare
}

// Order matters: helpers -> config -> audio -> app.
const js = ["src/music.js", "src/config.js", "src/audio.js", "src/app.js"]
  .map((f) => `// ===== ${f} =====\n${stripModuleSyntax(read(f))}`)
  .join("\n\n");

// Compile-check the concatenated script. Modules each have their own scope, so
// problems like two top-level `sleep` declarations only collide once inlined
// into a single <script>. Catch that here instead of shipping a dead page.
// (vm.Script compiles without executing, so browser globals are irrelevant.)
try {
  new vm.Script(js, { filename: "bundle.js" });
} catch (e) {
  console.error("Bundle failed to compile — not writing output:\n", e.message);
  process.exit(1);
}

const css = read("src/styles.css");

const banner =
  "<!-- GENERATED by build.js from dev.html + src/ — do not edit directly. -->";

const html = read("dev.html")
  .replace(/<!--[\s\S]*?-->\s*/, "")        // drop dev.html's source-note comment (first)
  .replace(/^<!DOCTYPE html>/i, `<!DOCTYPE html>\n${banner}`)
  .replace(/<link rel="stylesheet"[^>]*>/, `<style>\n${css}\n</style>`)
  .replace(/<script type="module"[^>]*><\/script>/, `<script>\n${js}\n</script>`);

const targets = ["index.html", "dist/interval-training.html"];
for (const t of targets) {
  const out = path.join(root, t);
  fs.mkdirSync(path.dirname(out), { recursive: true });
  fs.writeFileSync(out, html);
  console.log(`Wrote ${t} (${(html.length / 1024).toFixed(1)} kB)`);
}
